# Generated by Django 4.2.5 on 2023-10-04 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_remove_country_photo_country_area_country_capital_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='popular',
            field=models.IntegerField(default=0),
        ),
    ]
