# Generated by Django 4.2.5 on 2023-10-04 16:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_country_popular'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='grade',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='trip',
            name='grade',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
